### PR TITLE
Add support for auth method

### PR DESCRIPTION
**Pull request by HugoMaster**
Add support for sasl mechanism
Disable security as we dont use it now

### CODE REVIEW

**Comment by HugoMaster** [comment]
@nicolai86 This PR is only for other devs to work with our chat server.

**Comment by HugoMaster** [comment]
@zined @mortik

**Comment by HugoMaster** [comment]
Or is there a better way to have npm all the stuff with master and this branch?

**Comment by nicolai86** [comment]
I don't think we should merge this but I also don't have a great idea on how to have this without merging it. Ideas @mortik  @zined  ?

**Comment by nicolai86** [comment]
@HugoMaster let's wait until around noon, if no objections please merge & proceed

**Comment by HugoMaster** [comment]
@nicolai86 Is smth changed on server? It start working without this modifications.

**Comment by HugoMaster** [comment]
Now its only need disabled TLS, no need to modificate SASLMechanism

**Comment by nicolai86** [comment]
@HugoMaster is this required ATM? not sure about the status of this PR

**Pull request closed without merging**
